### PR TITLE
Hide items in fog of war

### PR DESCRIPTION
**Pull request by ThyWoof**

### CODE REVIEW

**Comment by ThyWoof** [comment]
@PhilPJL : need tweaks... it's indeed hiding the gadgets but not displaying, for example, lore plaques on walls after area is discovered.

**Comment by PhilPJL** [comment]
It works a bit, but for example pressing ALT reveals things not yet in view

image

Try this with "A3 Stockade of the Slave Lords"
[QuickSave_5.zip](https://github.com/ChrisPJohn/SolastaCommunityExpansion/files/7870476/QuickSave_5.zip)

**Comment by ThyWoof** [comment]
image
setting off

**Comment by ThyWoof** [comment]
image
this is the problem I'm facing... Anything attached to a wall doesn't get calculated correctly. I might need to re-implement the method I'm calling for visibility.

**Comment by ThyWoof** [comment]
image
now we can see the virtual entrance on wall again

**Comment by ThyWoof** [comment]
I left the original solution as a comment. Original solution won't highlight closed doors in field of view but is a bit faster compared to the actual.

What is your take @PhilPJL ? I haven't noticed any drops in FPS with ALT pressed.

**Comment by ThyWoof** [comment]
image
on

**Comment by ThyWoof** [comment]
image
off

**Review by ChrisPJohn — APPROVED** [review]

**Pull request merged**
