### PR TITLE
Fix tactician pool

### PR DESCRIPTION
**Pull request by ChrisPJohn**

### CODE REVIEW

**Comment by ThyWoof** [comment]
Leaving to @PhilPJL for approval.

**Review by PhilPJL — COMMENTED** [review]
Ok, doing my best to understand this stuff :)

General comment.  Using LINQ is generally terser and more easily understood, e.g.

```
// not Linq
RulesetUsablePower rulesetUsablePower = null;
foreach (RulesetUsablePower rulesetUsablePower2 in hero.UsablePowers)
{
    if (rulesetUsablePower2.PowerDefinition == featureDefinitionPower)
    {
        rulesetUsablePower = rulesetUsablePower2;
        break;
    }
}
```

```
// Linq
var rulesetUsablePower = hero.UsablePowers
    .FirstOrDefault(up => up.PowerDefinition == featureDefinitionPower);
```

**Review by PhilPJL — COMMENTED** [review]
You can do this

```
foreach (var featureDefinitionPower in hero.FeaturesToBrowse.Cast<FeatureDefinitionPower>())
{

instead of 

foreach (FeatureDefinition featureDefinitionPower in hero.FeaturesToBrowse.Cast<FeatureDefinitionPower>())
{
    FeatureDefinitionPower featureDefinitionPower = (FeatureDefinitionPower)featureDefinition;
```

**Comment by PhilPJL** [comment]
`class RulesetCharacterPatch` should be a static class (since all members are static).  You could then make `UpdateUsageForPowerPool` an extension method (if you like extension methods).

**Comment by PhilPJL** [comment]
Instead of using Tactician.SetupPowers(), initialising the feature definitions inline may be better since we can make them readonly and are guaranteed to be initialised once.

```
...
public **readonly** static FeatureDefinitionPowerSharedPool KnockDownPower = GambitResourcePoolBuilder.CreateAndAddToDB();
....
```

**Review by PhilPJL — DISMISSED** [review]
Ok as far as I can tell.  Comments are just things that could be tidied up at some point.

**Comment by ChrisPJohn** [comment]
> `class RulesetCharacterPatch` (and other classes) should be a static class (since all members are static). You could then make `UpdateUsageForPowerPool` (and other methods) an extension method (if you like extension methods).

I think everything else is already static, though I might have missed something.

**Comment by ChrisPJohn** [comment]
> Instead of using Tactician.SetupPowers(), initialising the feature definitions inline may be better since we can make them readonly and are guaranteed to be initialised once.
> 
> ```
> ...
> public **readonly** static FeatureDefinitionPowerSharedPool KnockDownPower = GambitResourcePoolBuilder.CreateAndAddToDB();
> ....
> ```

The order they are initialized is actually very important in this case. 

> Ok, doing my best to understand this stuff :)
> 
> General comment. Using LINQ is generally terser and more easily understood, e.g.
> 
> ```
> // not Linq
> RulesetUsablePower rulesetUsablePower = null;
> foreach (RulesetUsablePower rulesetUsablePower2 in hero.UsablePowers)
> {
>     if (rulesetUsablePower2.PowerDefinition == featureDefinitionPower)
>     {
>         rulesetUsablePower = rulesetUsablePower2;
>         break;
>     }
> }
> ```
> 
> ```
> // Linq
> var rulesetUsablePower = hero.UsablePowers
>     .FirstOrDefault(up => up.PowerDefinition == featureDefinitionPower);
> ```

Yeah, I should probably know LINQ better. I spent a long time working in a C# environment that I couldn't use stuff like LINQ, I sometimes still forget it's available.

**Comment by ChrisPJohn** [comment]
I cleaned up some of the code,

**Review by PhilPJL — COMMENTED** [review]
Ok looks good. What I meant about the static was add static like you did
`static class RulesetCharacterPatch`
and then you have the option to do 
`public static void UpdateUsageForPowerPool(**this** RulesetCharacter character, RulesetUsablePower modifiedPower, int poolUsage)`
so you can write
`character.UpdateUsageForPowerPool(...)`

**Comment by PhilPJL** [comment]
Erm, this 

```
private static void LookForFeatureOrigin(RulesetCharacterHero hero, FeatureDefinition featureDefinition, out CharacterRaceDefinition raceDefinition, out CharacterClassDefinition classDefinition, out FeatDefinition featDefinition)

...

			foreach (FeatDefinition featDefinition2 in hero.TrainedFeats)
			{
				if (**featDefinition**.Features.Contains(featureDefinition))
                {
					featDefinition = featDefinition2;
					return;
				}
			}
```


featDefinition will be null at that point.

**Comment by PhilPJL** [comment]
Now we can use tuples, out parameters are less desirable.

```
        private static RulesetUsablePower BuildUsablePower(RulesetCharacterHero hero, FeatureDefinitionPower featureDefinitionPower)
        {
            var (originRace, originClass, _) = LookForFeatureOrigin(hero, featureDefinitionPower);

            RulesetUsablePower rulesetUsablePower = new RulesetUsablePower(featureDefinitionPower, originRace, originClass);

            switch (featureDefinitionPower.RechargeRate)
            {
                case RuleDefinitions.RechargeRate.ChannelDivinity:
                    rulesetUsablePower.UsesAttribute = hero.GetAttribute("ChannelDivinityNumber", false);
                    break;
                case RuleDefinitions.RechargeRate.HealingPool:
                    rulesetUsablePower.UsesAttribute = hero.GetAttribute("HealingPool", false);
                    break;
                case RuleDefinitions.RechargeRate.SorceryPoints:
                    rulesetUsablePower.UsesAttribute = hero.GetAttribute("SorceryPoints", false);
                    break;
                default:
                    if (featureDefinitionPower.UsesDetermination == RuleDefinitions.UsesDetermination.AbilityBonusPlusFixed)
                    {
                        rulesetUsablePower.UsesAttribute = hero.GetAttribute(featureDefinitionPower.UsesAbilityScoreName, false);
                    }
                    else if (featureDefinitionPower.UsesDetermination == RuleDefinitions.UsesDetermination.ProficiencyBonus)
                    {
                        rulesetUsablePower.UsesAttribute = hero.GetAttribute("ProficiencyBonus", false);
                    }

                    break;
            }
            
            rulesetUsablePower.Recharge();

            return rulesetUsablePower;
        }

        private static (CharacterRaceDefinition raceDefinition, CharacterClassDefinition classDefinition, FeatDefinition featDefinition) LookForFeatureOrigin(RulesetCharacterHero hero, FeatureDefinition featureDefinition)
        {
            if (hero.RaceDefinition.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
            {
                return (hero.RaceDefinition, null, null);
            }

            if (hero.SubRaceDefinition != null &&
                hero.SubRaceDefinition.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
            {
                return (hero.SubRaceDefinition, null, null);
            }

            foreach (KeyValuePair<CharacterClassDefinition, int> keyValuePair in hero.ClassesAndLevels)
            {
                if (keyValuePair.Key.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
                {
                    return (null, keyValuePair.Key, null);
                }

                if (hero.ClassesAndSubclasses.ContainsKey(keyValuePair.Key) && hero.ClassesAndSubclasses[keyValuePair.Key] != null)
                {
                    if (hero.ClassesAndSubclasses[keyValuePair.Key].FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
                    {
                        return (null, keyValuePair.Key, null);
                    }
                }
            }

            return (null, null, hero.TrainedFeats.FirstOrDefault(tf => tf.Features.Contains(featureDefinition)));
        }
    }
```

**Comment by PhilPJL** [comment]
I notice that this

` RulesetUsablePower rulesetUsablePower = new RulesetUsablePower(featureDefinitionPower, originRace, originClass);
`

could pass featureDefinitionPower = null, which will cause a null ref exception.

**Comment by PhilPJL** [comment]
Not convinced these collection properties will always be initialised.  Probably need ?.

`return (null, null, hero.TrainedFeats?.FirstOrDefault(tf => tf.Features?.Contains(featureDefinition) == true));
`

**Comment by ChrisPJohn** [comment]
> Erm, this
> 
> ```
> private static void LookForFeatureOrigin(RulesetCharacterHero hero, FeatureDefinition featureDefinition, out CharacterRaceDefinition raceDefinition, out CharacterClassDefinition classDefinition, out FeatDefinition featDefinition)
> 
> ...
> 
> foreach (FeatDefinition featDefinition2 in hero.TrainedFeats)
> {
>    if (**featDefinition**.Features.Contains(featureDefinition))
>    {
>       featDefinition = featDefinition2;
> 	return;
>    }
> }
> ```
> 
> featDefinition will be null at that point. Did you mean featDefinition2?

Good catch all of the power pools I've tested with came from a class/subclass so the code never reached there.

**Comment by ChrisPJohn** [comment]
> I notice that this
> 
> `RulesetUsablePower rulesetUsablePower = new RulesetUsablePower(featureDefinitionPower, originRace, originClass);`
> 
> could pass featureDefinitionPower = null, which will cause a null ref exception.

Unless I'm missing something I don't see how featureDefinitionPower would ever be null there.

**Comment by ChrisPJohn** [comment]
Done.


> Now we can use tuples, out parameters are less desirable. We can rewrite these two methods like this
> 
> ```
>         private static RulesetUsablePower BuildUsablePower(RulesetCharacterHero hero, FeatureDefinitionPower featureDefinitionPower)
>         {
>             var (originRace, originClass, _) = LookForFeatureOrigin(hero, featureDefinitionPower);
> 
>             RulesetUsablePower rulesetUsablePower = new RulesetUsablePower(featureDefinitionPower, originRace, originClass);
> 
>             switch (featureDefinitionPower.RechargeRate)
>             {
>                 case RuleDefinitions.RechargeRate.ChannelDivinity:
>                     rulesetUsablePower.UsesAttribute = hero.GetAttribute("ChannelDivinityNumber", false);
>                     break;
>                 case RuleDefinitions.RechargeRate.HealingPool:
>                     rulesetUsablePower.UsesAttribute = hero.GetAttribute("HealingPool", false);
>                     break;
>                 case RuleDefinitions.RechargeRate.SorceryPoints:
>                     rulesetUsablePower.UsesAttribute = hero.GetAttribute("SorceryPoints", false);
>                     break;
>                 default:
>                     if (featureDefinitionPower.UsesDetermination == RuleDefinitions.UsesDetermination.AbilityBonusPlusFixed)
>                     {
>                         rulesetUsablePower.UsesAttribute = hero.GetAttribute(featureDefinitionPower.UsesAbilityScoreName, false);
>                     }
>                     else if (featureDefinitionPower.UsesDetermination == RuleDefinitions.UsesDetermination.ProficiencyBonus)
>                     {
>                         rulesetUsablePower.UsesAttribute = hero.GetAttribute("ProficiencyBonus", false);
>                     }
> 
>                     break;
>             }
>             
>             rulesetUsablePower.Recharge();
> 
>             return rulesetUsablePower;
>         }
> 
>         private static (CharacterRaceDefinition raceDefinition, CharacterClassDefinition classDefinition, FeatDefinition featDefinition) LookForFeatureOrigin(RulesetCharacterHero hero, FeatureDefinition featureDefinition)
>         {
>             if (hero.RaceDefinition.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
>             {
>                 return (hero.RaceDefinition, null, null);
>             }
> 
>             if (hero.SubRaceDefinition != null &&
>                 hero.SubRaceDefinition.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
>             {
>                 return (hero.SubRaceDefinition, null, null);
>             }
> 
>             foreach (KeyValuePair<CharacterClassDefinition, int> keyValuePair in hero.ClassesAndLevels)
>             {
>                 if (keyValuePair.Key.FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
>                 {
>                     return (null, keyValuePair.Key, null);
>                 }
> 
>                 if (hero.ClassesAndSubclasses.ContainsKey(keyValuePair.Key) && hero.ClassesAndSubclasses[keyValuePair.Key] != null)
>                 {
>                     if (hero.ClassesAndSubclasses[keyValuePair.Key].FeatureUnlocks.Any(unlock => unlock.FeatureDefinition == featureDefinition))
>                     {
>                         return (null, keyValuePair.Key, null);
>                     }
>                 }
>             }
> 
>             return (null, null, hero.TrainedFeats.FirstOrDefault(tf => tf.Features.Contains(featureDefinition)));
>         }
>     }
> ```

**Review by PhilPJL — APPROVED** [review]
My mistake on the null-ref featureDefinitionPower.

**Pull request merged**
