### PR TITLE
prototype

### PR DESCRIPTION
**Pull request by PhilPJL**
Idea for further automated documentation generation.
PR for comments only.

### CODE REVIEW

**Comment by ThyWoof** [comment]
Nice idea. I can also research if I can make tooltips leveraging this data.

**Review by ChrisPJohn — COMMENTED** [review]
I like the idea of having a technical solution to keeping documentation up to date. I've added a few comments.

**Review by ChrisPJohn — APPROVED** [review]
I'm marking approve because I like the idea and would love to see us make settings/documentation easier to do. I recognize we likely don't want to merge this specific pull.

**Comment by PhilPJL** [comment]
Closing for now

**Pull request closed without merging**
