### PR TITLE
Add custom proxy to Protect Threshold

### LINKED ISSUE #431: Spell tooltips need to be set
For example Bazou's 'Protect Threshold' which is base on 'Spike Growth'

image

### PR DESCRIPTION
**Pull request by PhilPJL**
Closes #431 

image

### CODE REVIEW

**Comment by PhilPJL** [comment]
Could be added to Dev branch also.

**Comment by ChrisPJohn** [comment]
> Could be added to Dev branch also.

I made a pull for this on dev. Lets add it there so that we can release it with our next release. We can merge it up to beta once it's checked in.

**Comment by ChrisPJohn** [comment]
https://github.com/ChrisPJohn/SolastaCommunityExpansion/pull/442

**Review by ThyWoof — APPROVED** [review]

**Comment by ThyWoof** [comment]
Approved but shouldn’t we merge into dev?

**Comment by ThyWoof** [comment]
closing this one in favor of #442

**Pull request closed without merging**
