### PR TITLE
adds experience slider multipler

### PR DESCRIPTION
**Pull request by ThyWoof**

### CODE REVIEW

**Comment by ThyWoof** [comment]
image

**Comment by PhilPJL** [comment]
I think you need to do this 

```
                // Never reduce to zero
                experiencePoints = (int)Math.Round(experiencePoints * Main.Settings.ReceivedExperiencePercentage / 100.0f, MidpointRounding.AwayFromZero);

```

**Comment by PhilPJL** [comment]
and also take into account experience can be granted by FunctorGrantExperience.

I was going to do 

```
    [HarmonyPatch(typeof(FunctorGrantExperience), "Execute")]
    internal static class FunctorGrantExperience_Execute_Patcher
    {
        internal static bool InFunctor { get; private set; }

        public static void Prefix()
        {
            InFunctor = true;
        }

        public static void Postfix()
        {
            InFunctor = false;
        }
    }

    [HarmonyPatch(typeof(RulesetCharacterHero), "GrantExperience")]
    internal static class RulesetCharacterHero_GrantExperience_Patcher
    {
        /// <summary>
        /// Modify experience received from battle by desired %.
        /// Don't modify if experience granted by FunctorGrantExperience.
        /// Don't reduce to zero.
        /// </summary>
        /// <param name="experiencePoints"></param>
        public static void Prefix(ref int experiencePoints)
        {
            if (!FunctorGrantExperience_Execute_Patcher.InFunctor 
                && Main.Settings.ReceivedExperiencePercentage != 100
                && Main.Settings.ReceivedExperiencePercentage != 0)
            {
                // Never reduce to zero
                experiencePoints = (int)Math.Round(experiencePoints * Main.Settings.ReceivedExperiencePercentage / 100.0f, MidpointRounding.AwayFromZero);
            }
        }
    }

```

**Comment by ThyWoof** [comment]
I don't believe we need to patch the Functor at all. I leveraged your experience formula as well as the if != 100.

**Comment by ThyWoof** [comment]
FunctorGrantExperience doesn't do it directly but always calling RulesetCharacterHero.GrantExperience. Reason why no patch required there:

    List<RulesetCharacterHero> rulesetCharacterHeroList = ServiceRepository.GetService<IGameService>().EnumerateHeroes();
    FunctorDefinitions.GrantExperienceMode intParameter = (FunctorDefinitions.GrantExperienceMode) functorParameters.IntParameter;
    using (List<RulesetCharacterHero>.Enumerator enumerator = rulesetCharacterHeroList.GetEnumerator())
    {
      while (enumerator.MoveNext())
      {
        RulesetCharacterHero current = enumerator.Current;
        if (intParameter == FunctorDefinitions.GrantExperienceMode.Flat)
        {
          current.GrantExperience(functorParameters.IntParameter2);
        }
        else
        {
          int experienceToReachLevel = current.ComputeNeededExperienceToReachLevel(functorParameters.IntParameter2);
          if (experienceToReachLevel > 0)
            current.GrantExperience(experienceToReachLevel);
        }
      }
      yield break;

**Comment by PhilPJL** [comment]
Yes but this branch forces you to the next level, which it won't if scaled.

    {
      int experienceToReachLevel = current.ComputeNeededExperienceToReachLevel(functorParameters.IntParameter2);
      if (experienceToReachLevel > 0)
        current.GrantExperience(experienceToReachLevel);
    }

So we could disable scaling when xp granted from functor and/or look at the "intParameter == FunctorDefinitions.GrantExperienceMode.Flat" so we still scale that bit.

**Review by PhilPJL — APPROVED** [review]

**Review by ChrisPJohn — APPROVED** [review]

**Review by PhilPJL — APPROVED** [review]
Will need to manually fix up DisplayTools after merge issue

**Pull request merged**
