### PR TITLE
refactor upcast conjured elemental or fey

### PR DESCRIPTION
**Pull request by ThyWoof**
. Feature now patches 2 methods instead of 3;
. Improved performance as `SpellDefinition.SubspellsList` patch was getting called 3 times from `SubSpellSelectionModal.Bind`. Now it gets cached once and reused;

### CODE REVIEW

**Review by PhilPJL — CHANGES_REQUESTED** [review]
Doesn't work :)

**Comment by ThyWoof** [comment]
@PhilPJL : couldn't open the shared save file but revisited the logic and indeed it was incorrectly filtering spells so I hope this change fixes it. please review with your save.

**Review by ChrisPJohn — APPROVED** [review]
The changes look fine. I assume they were verified in game.

**Comment by ThyWoof** [comment]
It’s now working after I got the save file from @PhilPJL. Shared some screenshots as well but prefer him to do the final merge

**Review by PhilPJL — APPROVED** [review]
Works correctly now

**Pull request merged**
